// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH_Q2rvQWaBEkoL1aux3wjkv4Ykre2zEo',
    appId: '1:565121069720:web:6efbcf52a78021fc76d6ed',
    messagingSenderId: '565121069720',
    projectId: 'food-delivery-c36c6',
    authDomain: 'food-delivery-c36c6.firebaseapp.com',
    storageBucket: 'food-delivery-c36c6.firebasestorage.app',
    measurementId: 'G-JGGNQ9QEJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaWnE55F62x9Sx_5G7alOUdJIXlFrIO4s',
    appId: '1:565121069720:android:a70627ed17f7e7b476d6ed',
    messagingSenderId: '565121069720',
    projectId: 'food-delivery-c36c6',
    storageBucket: 'food-delivery-c36c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJBjKAzCYn77sHC2Q7QUWd79mk7jdiuQ',
    appId: '1:565121069720:ios:f8e8d563a0283abc76d6ed',
    messagingSenderId: '565121069720',
    projectId: 'food-delivery-c36c6',
    storageBucket: 'food-delivery-c36c6.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiJBjKAzCYn77sHC2Q7QUWd79mk7jdiuQ',
    appId: '1:565121069720:ios:f8e8d563a0283abc76d6ed',
    messagingSenderId: '565121069720',
    projectId: 'food-delivery-c36c6',
    storageBucket: 'food-delivery-c36c6.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH_Q2rvQWaBEkoL1aux3wjkv4Ykre2zEo',
    appId: '1:565121069720:web:e59f4dbf44780c7576d6ed',
    messagingSenderId: '565121069720',
    projectId: 'food-delivery-c36c6',
    authDomain: 'food-delivery-c36c6.firebaseapp.com',
    storageBucket: 'food-delivery-c36c6.firebasestorage.app',
    measurementId: 'G-22FMVKYPN8',
  );
}
